services:
  backend:
    image: bboti86/crimson-cycle-backend:latest
    volumes:
      - ./backend/data:/app/data
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: bboti86/crimson-cycle-frontend:latest
    ports:
      - "8888:80"
    depends_on:
      - backend
    restart: always

volumes:
  database:
