services:
  backend:
    build: ./backend
    container_name: crimson-cycle-backend
    volumes:
      - ./backend/data:/app/data
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    container_name: crimson-cycle-frontend
    ports:
      - "8888:80"
    depends_on:
      - backend
    restart: always

volumes:
  database:
